In [5]:
import sqlite3
import pandas as pd
import numpy as np

In [6]:

con_food = sqlite3.connect("..\\data\\food_lens_app.db")
cur_food = con_food.cursor()

In [7]:
### With Pandas
df = pd.read_sql("select * from foodlens_records_dev", con_food)
df

,user_id,timestamp,calories,carbs_g,create_timestamp,fat_g,food_item,meal_date,meal_type,portion,protein_g,saturated_fat_g
0,songyangholmes,2025-05-03|094919|Soft-boiled egg,70,1.0,2025-05-03T09:49:19.806210,5.0,Soft-boiled egg,2025-05-03,Breakfast,1 large egg (50g),6.0,1.5
1,songyangholmes,2025-05-03|094919|Soy sauce,10,1.0,2025-05-03T09:49:19.806210,0.0,Soy sauce,2025-05-03,Breakfast,1 tablespoon (15g),1.0,0.0
2,songyangholmes,2025-05-03|094919|Condensed milk,60,10.0,2025-05-03T09:49:19.806210,2.0,Condensed milk,2025-05-03,Breakfast,1 tablespoon (20g),1.0,1.0
3,songyangholmes,2025-05-03|094919|Total Meal,140,12.0,2025-05-03T09:49:19.806210,7.0,Total Meal,2025-05-03,Breakfast,-,8.0,3.5
4,User Name,2025-05-03|101519|Toast (2 slices),160,30.0,2025-05-03T10:15:19.919055,2.0,Toast (2 slices),2025-05-03,Snack,2 slices,6.0,0.5
5,User Name,2025-05-03|101519|Butter (1 pat),72,0.0,2025-05-03T10:15:19.919055,8.0,Butter (1 pat),2025-05-03,Snack,1 pat (10g),0.1,5.0
6,User Name,2025-05-03|101519|Jam (1 tablespoon),50,13.0,2025-05-03T10:15:19.919055,0.0,Jam (1 tablespoon),2025-05-03,Snack,1 tablespoon (20g),0.0,0.0
7,User Name,2025-05-03|101519|Total Meal,282,53.0,2025-05-03T10:15:19.919055,10.0,Total Meal,2025-05-03,Snack,-,6.1,5.5

In [5]:
con_email = sqlite3.connect("..\\data\\foodlens_gmail_whitelist_dev.db")
cur_email = con_email.cursor()

df = pd.read_sql("select * from foodlens_gmail_whitelist_dev", con_email)
df

                    user_id                            timestamp
0  songyangholmes@gmail.com  2025-05-03 09:37:57|I am the author